name: Electron Demo Test Run

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * MON-FRI'
  push:
    branches:
    - main
    paths:
    - '**/electron/**'
    - '.github/workflows/electron-tests.yml'
  pull_request:
    branches:
    - main
    paths:
    - '**/electron/**'
    - '.github/workflows/electron-tests.yml'

jobs:
  electron-test-run:
    runs-on: macos-latest

    steps:
    - name: Checkout (including submodules)
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Cache tests history
      uses: actions/cache@v5
      with:
        save-always: true
        path: output/history
        key: tests-history-cache
        restore-keys: |
          tests-history-cache

    - name: Install VS code
      run: brew install --cask visual-studio-code

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
        cache: 'gradle'

    - name: Run Electron tests
      run: |
        ./gradlew runStories -Pvividus.configuration.suites=electron \
                             -Pvividus.configuration.profiles=desktop/electron,web/desktop/chrome

    - name: Publish Electron tests report
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: Electron tests report
        path: output/reports/allure
